export interface Game {
  id: string;
  title: string;
  category: string;
  thumbnail: string;
  url: string;
  iframeUrl: string;
  description: string;
  plays: string;
  rating: number;
  isNew?: boolean;
  isHot?: boolean;
  isFeatured?: boolean;
}

export const categories = [
  "All", "Action", "Puzzle", "Racing", "Sports", "Adventure", "Arcade", "Shooting", "Strategy", "Casual"
];

export const games: Game[] = [
  // ── EXISTING GAMES ──────────────────────────────────────────
  {
    id: "1",
    title: "Slope",
    category: "Arcade",
    thumbnail: "https://img.gamemonetize.com/qdz2yqfhf3e4xbp6vl0emjxwtd5j2yjz/512x384.jpg",
    url: "/game/slope",
    iframeUrl: "https://slope-game.github.io/",
    description: "Roll down the slope, dodge obstacles at high speed!",
    plays: "12.4M",
    rating: 4.8,
    isHot: true,
    isFeatured: true,
  },
  {
    id: "2",
    title: "2048",
    category: "Puzzle",
    thumbnail: "https://img.gamemonetize.com/u4kwhz1ytpf3vf2qhb1r7d0gqpvt9kl3/512x384.jpg",
    url: "/game/2048",
    iframeUrl: "https://play2048.co/",
    description: "Combine tiles to reach 2048. Simple but addictive!",
    plays: "8.2M",
    rating: 4.6,
    isFeatured: true,
  },
  {
    id: "3",
    title: "Subway Surfers",
    category: "Action",
    thumbnail: "https://img.gamemonetize.com/t7nkpxq3yz8vd1c5fh0wsb4r6m2jg9ae/512x384.jpg",
    url: "/game/subway-surfers",
    iframeUrl: "https://subwaysurf.io/",
    description: "Run, dodge and surf through the subway!",
    plays: "25.1M",
    rating: 4.9,
    isHot: true,
  },
  {
    id: "4",
    title: "Moto X3M",
    category: "Racing",
    thumbnail: "https://img.gamemonetize.com/5f8c2a3b7e9d1h4k6j0m/512x384.jpg",
    url: "/game/moto-x3m",
    iframeUrl: "https://www.crazygames.com/embed/moto-x3m",
    description: "Extreme bike racing with insane stunts!",
    plays: "6.7M",
    rating: 4.7,
    isNew: true,
  },
  {
    id: "5",
    title: "Snake Game",
    category: "Casual",
    thumbnail: "https://img.gamemonetize.com/s9p2q7t4u1v6w3x0y8z/512x384.jpg",
    url: "/game/snake",
    iframeUrl: "https://playsnake.org/",
    description: "Classic snake game. Eat, grow, survive!",
    plays: "4.1M",
    rating: 4.4,
  },
  {
    id: "6",
    title: "Tetris",
    category: "Puzzle",
    thumbnail: "https://img.gamemonetize.com/r5n8l2k9j6h3g0f7e4d/512x384.jpg",
    url: "/game/tetris",
    iframeUrl: "https://tetris.com/play-tetris",
    description: "The legendary block stacking puzzle game!",
    plays: "15.3M",
    rating: 4.9,
    isHot: true,
  },
  {
    id: "7",
    title: "Basketball Stars",
    category: "Sports",
    thumbnail: "https://img.gamemonetize.com/b1c4d7e0f3g6h9i2j5/512x384.jpg",
    url: "/game/basketball-stars",
    iframeUrl: "https://www.crazygames.com/embed/basketball-stars",
    description: "Dunk, shoot and dominate the court!",
    plays: "3.9M",
    rating: 4.5,
    isNew: true,
  },
  {
    id: "8",
    title: "Minecraft Classic",
    category: "Adventure",
    thumbnail: "https://img.gamemonetize.com/mc1a2b3c4d5e6f7g8h9/512x384.jpg",
    url: "/game/minecraft-classic",
    iframeUrl: "https://classic.minecraft.net/",
    description: "Build, create and survive in pixel world!",
    plays: "20.5M",
    rating: 4.8,
    isFeatured: true,
    isHot: true,
  },
  {
    id: "9",
    title: "Agar.io",
    category: "Action",
    thumbnail: "https://img.gamemonetize.com/ag9o8n7m6l5k4j3i2h/512x384.jpg",
    url: "/game/agario",
    iframeUrl: "https://agar.io/",
    description: "Eat smaller cells, grow bigger, dominate!",
    plays: "18.7M",
    rating: 4.6,
  },
  {
    id: "10",
    title: "Cut The Rope",
    category: "Puzzle",
    thumbnail: "https://img.gamemonetize.com/ct1r2o3p4e5t6h7r8p/512x384.jpg",
    url: "/game/cut-the-rope",
    iframeUrl: "https://www.crazygames.com/embed/cut-the-rope-remastered",
    description: "Feed the candy to Om Nom by cutting ropes!",
    plays: "7.2M",
    rating: 4.7,
    isNew: true,
  },
  {
    id: "11",
    title: "Drift Boss",
    category: "Racing",
    thumbnail: "https://img.gamemonetize.com/db1o2s3s4r5a6c7i8n/512x384.jpg",
    url: "/game/drift-boss",
    iframeUrl: "https://www.crazygames.com/embed/drift-boss",
    description: "Master the art of drifting on endless roads!",
    plays: "5.5M",
    rating: 4.5,
  },
  {
    id: "12",
    title: "Stickman Hook",
    category: "Arcade",
    thumbnail: "https://img.gamemonetize.com/sh1t2i3c4k5m6a7n8h/512x384.jpg",
    url: "/game/stickman-hook",
    iframeUrl: "https://www.crazygames.com/embed/stickman-hook",
    description: "Swing through levels like a stickman superhero!",
    plays: "9.1M",
    rating: 4.8,
    isHot: true,
  },

  // ── NEW GAMES ────────────────────────────────────────────────
  {
    id: "13",
    title: "Temple Run 2",
    category: "Action",
    thumbnail: "https://img.gamemonetize.com/tr2a1b2c3d4e5f6g7h8/512x384.jpg",
    url: "/game/temple-run-2",
    iframeUrl: "https://poki.com/en/g/temple-run-2",
    description: "Race through ancient temples, dodge traps and collect coins!",
    plays: "22.3M",
    rating: 4.8,
    isHot: true,
    isFeatured: true,
  },
  {
    id: "14",
    title: "Drive Mad",
    category: "Racing",
    thumbnail: "https://img.gamemonetize.com/dm1r2i3v4e5m6a7d8x/512x384.jpg",
    url: "/game/drive-mad",
    iframeUrl: "https://www.crazygames.com/embed/drive-mad",
    description: "Physics-based driving madness — don't flip over!",
    plays: "11.2M",
    rating: 4.8,
    isHot: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "15",
    title: "Level Devil",
    category: "Arcade",
    thumbnail: "https://img.gamemonetize.com/ld1e2v3e4l5d6e7v8il/512x384.jpg",
    url: "/game/level-devil",
    iframeUrl: "https://www.crazygames.com/embed/level-devil",
    description: "Rage platformer where the level itself tries to kill you!",
    plays: "8.9M",
    rating: 4.7,
    isHot: true,
    isNew: true,
  },
  {
    id: "16",
    title: "Retro Bowl",
    category: "Sports",
    thumbnail: "https://img.gamemonetize.com/rb1e2t3r4o5b6o7w8l/512x384.jpg",
    url: "/game/retro-bowl",
    iframeUrl: "https://www.crazygames.com/embed/retro-bowl",
    description: "Manage and play your own retro-style American football team!",
    plays: "14.6M",
    rating: 4.9,
    isHot: true,
    isFeatured: true,
  },
  {
    id: "17",
    title: "Monkey Mart",
    category: "Casual",
    thumbnail: "https://img.gamemonetize.com/mm1o2n3k4e5y6m7a8r/512x384.jpg",
    url: "/game/monkey-mart",
    iframeUrl: "https://www.crazygames.com/embed/monkey-mart",
    description: "Run your own supermarket as a busy little monkey!",
    plays: "10.4M",
    rating: 4.7,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "18",
    title: "Venge.io",
    category: "Shooting",
    thumbnail: "https://img.gamemonetize.com/vi1o2v3e4n5g6e7i8o/512x384.jpg",
    url: "/game/vengeio",
    iframeUrl: "https://venge.io/",
    description: "3D multiplayer FPS battle in your browser. Eliminate all enemies!",
    plays: "7.8M",
    rating: 4.6,
    isHot: true,
  },
  {
    id: "19",
    title: "Brain Test",
    category: "Puzzle",
    thumbnail: "https://img.gamemonetize.com/bt1r2a3i4n5t6e7s8t/512x384.jpg",
    url: "/game/brain-test",
    iframeUrl: "https://www.crazygames.com/embed/brain-test-tricky-puzzles",
    description: "Tricky puzzles that test your logic and creativity!",
    plays: "6.3M",
    rating: 4.6,
    isNew: true,
  },
  {
    id: "20",
    title: "Vectaria.io",
    category: "Adventure",
    thumbnail: "https://img.gamemonetize.com/ve1c2t3a4r5i6a7i8o/512x384.jpg",
    url: "/game/vectaria",
    iframeUrl: "https://vectaria.io/",
    description: "Multiplayer blocky sandbox — build, explore and battle!",
    plays: "5.1M",
    rating: 4.5,
    isNew: true,
  },
  {
    id: "21",
    title: "My Perfect Hotel",
    category: "Casual",
    thumbnail: "https://img.gamemonetize.com/mph1o2t3e4l5m6g7r8/512x384.jpg",
    url: "/game/my-perfect-hotel",
    iframeUrl: "https://www.crazygames.com/embed/my-perfect-hotel",
    description: "Build and manage your own dream hotel empire!",
    plays: "4.8M",
    rating: 4.5,
    isNew: true,
  },
  {
    id: "22",
    title: "Speed Stars",
    category: "Racing",
    thumbnail: "https://img.gamemonetize.com/ss1p2e3e4d5s6t7a8r/512x384.jpg",
    url: "/game/speed-stars",
    iframeUrl: "https://www.crazygames.com/embed/speed-stars",
    description: "Lightning-fast running races — time your sprints perfectly!",
    plays: "3.7M",
    rating: 4.4,
    isNew: true,
  },
  {
    id: "23",
    title: "Combat Online 2",
    category: "Shooting",
    thumbnail: "https://img.gamemonetize.com/co2m1b2a3t4o5n6l7y/512x384.jpg",
    url: "/game/combat-online-2",
    iframeUrl: "https://www.crazygames.com/embed/combat-online-2",
    description: "Online multiplayer shooter — team up and take the win!",
    plays: "6.1M",
    rating: 4.6,
    isHot: true,
  },
  {
    id: "24",
    title: "Blocky Blast Puzzle",
    category: "Puzzle",
    thumbnail: "https://img.gamemonetize.com/bbp1l2o3c4k5b6l7a8/512x384.jpg",
    url: "/game/blocky-blast-puzzle",
    iframeUrl: "https://www.crazygames.com/embed/blocky-blast-puzzle",
    description: "Place blocks to clear lines in this satisfying puzzle!",
    plays: "3.2M",
    rating: 4.4,
    isNew: true,
  },
  {
    id: "25",
    title: "Age of War",
    category: "Strategy",
    thumbnail: "https://img.gamemonetize.com/aow1g2e3w4a5r6a7g8/512x384.jpg",
    url: "/game/age-of-war",
    iframeUrl: "https://www.crazygames.com/embed/age-of-war",
    description: "Evolve your army through ages and destroy the enemy base!",
    plays: "9.5M",
    rating: 4.7,
    isHot: true,
  },
  {
    id: "26",
    title: "Bullet Force",
    category: "Shooting",
    thumbnail: "https://img.gamemonetize.com/bf1u2l3l4e5t6f7r8c/512x384.jpg",
    url: "/game/bullet-force",
    iframeUrl: "https://www.crazygames.com/embed/bullet-force-multiplayer",
    description: "Intense 3D multiplayer FPS with multiple weapons and maps!",
    plays: "8.4M",
    rating: 4.6,
    isHot: true,
  },
  {
    id: "27",
    title: "Angry Gran Run",
    category: "Action",
    thumbnail: "https://img.gamemonetize.com/agr1n2g3r4y5g6r7a8/512x384.jpg",
    url: "/game/angry-gran-run",
    iframeUrl: "https://www.crazygames.com/embed/angry-gran-run",
    description: "An angry grandma on the loose — run, smash and dodge!",
    plays: "2.9M",
    rating: 4.3,
  },
  {
    id: "28",
    title: "Apple Worm",
    category: "Puzzle",
    thumbnail: "https://img.gamemonetize.com/aw1p2p3l4e5w6o7r8m/512x384.jpg",
    url: "/game/apple-worm",
    iframeUrl: "https://poki.com/en/g/apple-worm",
    description: "Guide your worm to the apple in this mind-bending puzzle!",
    plays: "3.5M",
    rating: 4.5,
    isNew: true,
  },
  {
    id: "29",
    title: "Aquanaut",
    category: "Adventure",
    thumbnail: "https://img.gamemonetize.com/aq1u2a3n4a5u6t7a8q/512x384.jpg",
    url: "/game/aquanaut",
    iframeUrl: "https://www.crazygames.com/embed/aquanaut",
    description: "Dive into the deep ocean and discover hidden treasures!",
    plays: "2.1M",
    rating: 4.3,
    isNew: true,
  },
  {
    id: "30",
    title: "A Small World Cup",
    category: "Sports",
    thumbnail: "https://img.gamemonetize.com/swc1m2a3l4l5w6o7r8/512x384.jpg",
    url: "/game/small-world-cup",
    iframeUrl: "https://www.crazygames.com/embed/a-small-world-cup",
    description: "Ragdoll soccer chaos — score goals with wobbly players!",
    plays: "5.7M",
    rating: 4.6,
    isHot: true,
  },
  {
    id: "31",
    title: "Krunker.io",
    category: "Shooting",
    thumbnail: "https://img.gamemonetize.com/kr1u2n3k4e5r6i7o8k/512x384.jpg",
    url: "/game/krunkerio",
    iframeUrl: "https://krunker.io/",
    description: "Fast-paced pixelated multiplayer FPS — aim and fire!",
    plays: "13.2M",
    rating: 4.7,
    isHot: true,
    isFeatured: true,
  },
  {
    id: "32",
    title: "Slither.io",
    category: "Action",
    thumbnail: "https://img.gamemonetize.com/sl1i2t3h4e5r6i7o8s/512x384.jpg",
    url: "/game/slitherio",
    iframeUrl: "https://slither.io/",
    description: "Grow your snake by consuming glowing orbs. Don't crash!",
    plays: "16.8M",
    rating: 4.7,
    isHot: true,
  },
  {
    id: "33",
    title: "Fireboy and Watergirl",
    category: "Adventure",
    thumbnail: "https://img.gamemonetize.com/fw1i2r3e4b5o6y7w8g/512x384.jpg",
    url: "/game/fireboy-watergirl",
    iframeUrl: "https://www.crazygames.com/embed/fireboy-and-watergirl-1-forest-temple",
    description: "Two-player co-op puzzle platformer through elemental temples!",
    plays: "11.6M",
    rating: 4.8,
    isHot: true,
    isFeatured: true,
  },
  {
    id: "34",
    title: "Happy Wheels",
    category: "Casual",
    thumbnail: "https://img.gamemonetize.com/hw1a2p3p4y5w6h7e8l/512x384.jpg",
    url: "/game/happy-wheels",
    iframeUrl: "https://www.crazygames.com/embed/happy-wheels",
    description: "Ragdoll physics chaos on wheels — survive at all costs!",
    plays: "10.1M",
    rating: 4.5,
    isHot: true,
  },
  {
    id: "35",
    title: "Tower of Hanoi",
    category: "Strategy",
    thumbnail: "https://img.gamemonetize.com/th1o2w3e4r5h6a7n8o/512x384.jpg",
    url: "/game/tower-of-hanoi",
    iframeUrl: "https://www.crazygames.com/embed/tower-of-hanoi",
    description: "Classic disk-stacking logic puzzle. Move all disks to win!",
    plays: "1.8M",
    rating: 4.2,
  },
  {
    id: "36",
    title: "MR RACER",
    category: "Racing",
    thumbnail: "https://img.gamemonetize.com/mr1r2a3c4e5r6m7r8a/512x384.jpg",
    url: "/game/mr-racer",
    iframeUrl: "https://www.crazygames.com/embed/mr-racer",
    description: "High-speed highway racing with traffic dodge and upgrades!",
    plays: "4.4M",
    rating: 4.5,
    isNew: true,
  },
  {
    id: "37",
    title: "Stick Merge",
    category: "Action",
    thumbnail: "https://img.gamemonetize.com/sm1t2i3c4k5m6e7r8g/512x384.jpg",
    url: "/game/stick-merge",
    iframeUrl: "https://www.crazygames.com/embed/stick-merge",
    description: "Merge stick soldiers and send them to battle!",
    plays: "3.3M",
    rating: 4.4,
    isNew: true,
  },
  {
    id: "38",
    title: "Who Is?",
    category: "Puzzle",
    thumbnail: "https://img.gamemonetize.com/wi1o2i3s4w5h6o7i8s/512x384.jpg",
    url: "/game/who-is",
    iframeUrl: "https://www.crazygames.com/embed/who-is",
    description: "Spot the liar in tricky social situations. Think carefully!",
    plays: "2.7M",
    rating: 4.3,
    isNew: true,
  },
  {
    id: "39",
    title: "Rooftop Snipers",
    category: "Shooting",
    thumbnail: "https://img.gamemonetize.com/rs1o2o3f4t5o6p7s8n/512x384.jpg",
    url: "/game/rooftop-snipers",
    iframeUrl: "https://www.crazygames.com/embed/rooftop-snipers",
    description: "1v1 rooftop sniper duels — knock your opponent off the ledge!",
    plays: "7.3M",
    rating: 4.7,
    isHot: true,
  },
  {
    id: "40",
    title: "Crossy Road",
    category: "Arcade",
    thumbnail: "https://img.gamemonetize.com/cr1o2s3s4y5r6o7a8d/512x384.jpg",
    url: "/game/crossy-road",
    iframeUrl: "https://www.crazygames.com/embed/crossy-road",
    description: "Help the chicken cross the road, river and rails. Don't get hit!",
    plays: "9.8M",
    rating: 4.6,
    isHot: true,
    isFeatured: true,
  },
];

export const featuredGames = games.filter(g => g.isFeatured);
export const hotGames = games.filter(g => g.isHot);
export const newGames = games.filter(g => g.isNew);